name: ARM
version: "0.2.2"
slug: arm
description: Automatic Ripping Machine
link: https://github.com/mliradelc/ARM-HASS-Addon
arch:
  - amd64
  - aarch64
image: ghcr.io/mliradelc/arm-hass-addon
startup: application
boot: auto
init: true
ports:
  8089/tcp: 8089
ports_description:
  8089/tcp: ARM Web UI
watchdog: "http://[HOST]:8089"
webui: "http://[HOST]:[PORT:8089]"
options:
  web_port: 8089
schema:
  web_port: int
map:
  - addon_config:rw
  - share:rw
  - media:rw
devices:
  - /dev/dri
  - /dev/sr0
  - /dev/sg0
  - /dev/dri/renderD128
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
  - NET_ADMIN
panel_icon: mdi:compact-disc
panel_title: "ARM"
ingress: true
ingress_port: 8089
